openapi: 3.0.0
info:
  title: de:code 2020 Azure Quiz
  description: de:code 2020 Azure Quiz
  version: 1.0.0

servers:
  - url: '{logicAppsUrl}'
    description: LogicApps の URL
    variables:
      logicAppsUrl:
        default: <Input here>
        description: LogicApps の URL

paths:
  /:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier:
                  type: string
                  format: uuid
                question_id:
                  type: integer
                  minimum: 1
                answer_id:
                  type: string
                  pattern: 'a|b|c|d'
      responses:
        '202':
          description: Accepted
          content:
            application/text:
              schema:
                type: string
